########################################################################################
# Beispiel 1
#
# Erstellen Sie ein Dockerfile, welches nginx als Quelle nutzt.
# Erstellen und starten Sie den docker container.
#
# Image bauen: docker build -t demo:nginx_image .
# Image ausführen: docker run -p 8080:80 demo:nginx_image
########################################################################################

# fertiges nginx Image beziehen
########################################################################################
FROM nginx:alpine
